'needs-discussion':
  unlabel:
    - 'bug'
    - 'triage'
  comment: >
    **Please create a GitHub Discussion instead of this issue.**


    As this issue has been labeled as `needs-discussion` by a maintainer it is being automatically closed and locked. It will later be deleted to avoid polluting repository searches with duplicate or incorrect content.


    This doesn't necessarily mean that what you've reported isn't a problem or a reasonable idea, but it does mean that it should be raised as a Discussion first and not an Issue. _Please create a Discussion now, assuming you still wish to discuss it._


    Thanks, Azure DevOps Migration Tools team
  close: true
  lock: true
  lock-reason: 'resolved'


'needs-code-formatting':
  comment: >
    Hi, you need to format code or logs here so that they're more readable for others.


    You can find a Markdown code formatting guide [here](https://www.markdownguide.org/basic-syntax/#code) as well as some GitHub-specific information formatting code blocks [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).


    Thanks, Azure DevOps Migration Tools team

'retry-latest-version':
  comment: >
    Hi there,


    You're reporting a problem with an old version of the Azure DevOps Migration Tools.
    Please try the [latest](https://github.com/nkdAgility/azure-devops-migration-tools/releases/latest) version and tell us if that fixes your problem. Bonus points for also trying with the [latest preview](https://github.com/nkdAgility/azure-devops-migration-tools/releases/) version.


    Good luck,


    Thanks, Azure DevOps Migration Tools team

'needs-more-information':
  comment: >
    Hi there,


    **_ACTION REQUIRED_**


    In order for us to help you will need to provide both the log, and the configration file that you are using.


    **Generate and Attach Log** 


    Steps:


    1. In the Config file, change `LogLevel` to `Debug`.

    2. Identify a work item ID that exhibits this issue and create a query that only selects this work item.

    3. Delete any existing copy of that work item from the target.

    4. Run the migration.

    5. Comment here with the full Log attached as well as the full (redacted) configration file that you are using.


    Your assistance is greatly appreciated!


    Thanks,  
    Azure DevOps Migration Tools team

'needs-local-debug':
  comment: >
    Hi there,

    **_ACTION REQUIRED_**


    This looks to be a complex issue that you will need to debug locally to figure out what is going on.     


    **Debug in Visual Studio** 


    Steps:


    1. [Fork this repository](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project#forking-a-repository)

    2. [Open this project in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/get-started/tutorial-open-project-from-repo?view=vs-2022#open-a-project-from-a-github-repo)

    3. [Edit the Launch Profile](https://learn.microsoft.com/en-us/visualstudio/debugger/project-settings-for-csharp-debug-configurations-dotnetcore?view=vs-2022#launch-profile-net-core-net-5) to point to your config.<br />![image](https://github.com/nkdAgility/azure-devops-migration-tools/assets/5205575/1f55a278-8c8d-4481-8f2e-08d20640c8a8)

    4. Craft a [WIQL query](https://learn.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax) to only load the work item with the issue.

    5. Then [set some break points and debug](https://learn.microsoft.com/en-us/visualstudio/debugger/debugger-feature-tour) the issue.

    6. Comment here with the results.



    Your assistance is greatly appreciated!


    Thanks,  
    Azure DevOps Migration Tools team