# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - architecture
    - title: 👒 Architecture Improvements
      labels:
        - architecture
