optionsClassName: MultiValueConditionalMapConfig
optionsClassFullName: MigrationTools._EngineV1.Configuration.FieldMap.MultiValueConditionalMapConfig
configurationSamples:
- name: default
  description: 
  code: >-
    {
      "$type": "MultiValueConditionalMapConfig",
      "WorkItemTypeName": "*",
      "sourceFieldsAndValues": {
        "$type": "Dictionary`2",
        "Something": "SomethingElse"
      },
      "targetFieldsAndValues": {
        "$type": "Dictionary`2",
        "Something": "SomethingElse"
      }
    }
  sampleFor: MigrationTools._EngineV1.Configuration.FieldMap.MultiValueConditionalMapConfig
description: ??? If you know how to use this please send a PR :)
className: MultiValueConditionalMapConfig
typeName: FieldMaps
architecture: v1
options:
- parameterName: sourceFieldsAndValues
  type: Dictionary
  description: missng XML code comments
  defaultValue: missng XML code comments
- parameterName: targetFieldsAndValues
  type: Dictionary
  description: missng XML code comments
  defaultValue: missng XML code comments
- parameterName: WorkItemTypeName
  type: String
  description: missng XML code comments
  defaultValue: missng XML code comments
status: ready
processingTarget: Work Item Field
classFile: /src/MigrationTools/_EngineV1/Configuration/FieldMap/MultiValueConditionalMapConfig.cs
optionsClassFile: /src/MigrationTools/_EngineV1/Configuration/FieldMap/MultiValueConditionalMapConfig.cs
