optionsClassName: TfsTeamSettingsEndpointOptions
optionsClassFullName: MigrationTools.Endpoints.TfsTeamSettingsEndpointOptions
configurationSamples: []
description: missng XML code comments
className: TfsTeamSettingsEndpoint
typeName: Endpoints
architecture: v2
options: []
status: missng XML code comments
processingTarget: missng XML code comments
