optionsClassName: TestConfigurationsMigrationConfig
optionsClassFullName: MigrationTools._EngineV1.Configuration.Processing.TestConfigurationsMigrationConfig
configurationSamples:
- name: default
  description: 
  code: >-
    {
      "$type": "TestConfigurationsMigrationConfig",
      "Enabled": false
    }
  sampleFor: MigrationTools._EngineV1.Configuration.Processing.TestConfigurationsMigrationConfig
description: This processor can migrate `test configuration`. This should be run before `LinkMigrationConfig`.
className: TestConfigurationsMigrationContext
typeName: Processors
architecture: v1
options:
- parameterName: Enabled
  type: Boolean
  description: missng XML code comments
  defaultValue: missng XML code comments
status: Beta
processingTarget: Suites & Plans
classFile: /src/VstsSyncMigrator.Core/Execution/MigrationContext/TestConfigurationsMigrationContext.cs
optionsClassFile: /src/MigrationTools/_EngineV1/Configuration/Processing/TestConfigurationsMigrationConfig.cs
